<?php

/**
 * Implements hook_node_info().
 */
function questionnaire_node_info() {
  return array(
    'questionnaire' => array(
      'name' => t('Questionnaire'),
      'base' => 'node_content',
      'description' => t('List of all the questionnaires.'),
      'has_title' => TRUE,
      'title_label' => t('Title'),
    ),
    'question' => array(
      'name' => t('Questions'),
      'base' => 'node_content',
      'description' => t('List of all the questions.'),
      'has_title' => TRUE,
      'title_label' => t('Title'),
    ),
  );
}

/**
 * Implements hook_form().
 */
function questionnaire_form($node, &$form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_form_alter().
 */
function questionnaire_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'question_node_form':
      $form['#validate'][] = '_validate_answer';
      break;
  }
}

/**
 * Custom form validator for the Answer field.
 */
function _validate_answer($form, &$form_state) {
  $possible_answer = $form_state['input']['possible_answers'][LANGUAGE_NONE];
  $answer = $form_state['input']['actual_answer'][LANGUAGE_NONE][0]['value'];
  $list_of_answers = array();

  foreach ($possible_answer as $key => $panswer) {
    if ($panswer['value']) {
      $list_of_answers[] = $panswer['value'];
    }
  }

  if (!in_array($answer, $list_of_answers)) {
    form_set_error('actual_answer', 'Answer for this question should be one out of the options that you have added.');
  }
}
